name: api
description: "Api Plugin for Ghosten Player"
version: 1.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection: ^1.18.0
  date_format: ^2.0.0
  dio: ^5.7.0
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ghosten.api
        pluginClass: ApiPlugin
      web:
        pluginClass: ApiWeb
        fileName: src/api_web.dart
